"""Add model cards /user /deck

Revision ID: 66ec8390c0a5
Revises: 
Create Date: 2025-10-15 17:54:51.711628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ec8390c0a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('user_bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('access', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('creation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deck_image', sa.String(length=200), nullable=True),
    sa.Column('access_key', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('question', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modification', sa.DateTime(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gapfill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text1', sa.String(length=100), nullable=False),
    sa.Column('text2', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_alt', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qcm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_qcm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('qcm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qcm_id'], ['qcm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_qcm')
    op.drop_table('qcm')
    op.drop_table('qa')
    op.drop_table('image')
    op.drop_table('gapfill')
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('user')
    # ### end Alembic commands ###
